# Travis CI pelican deploy guide:
# https://zonca.github.io/2013/09/automatically-build-pelican-and-publish-to-github-pages.html
branches:
  only:
  - src
language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
script:
  - make html
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
  - secure: Q1gaHeD6DQKXaZD13JOw/4MohHeTV9e3oN0tiDXqSyiT7tZSkx5h+Tk8ikzbfXIhKxmDh7Nym53i2lY16Wuz3txaYQuKdChtqx+Ks9Jvb7j8CW6Dw6z4ZXdggzpCEGh0h8c06o9fkbXlwnVWJyGEol1CfPXeEPOaAlT197/e5riOH0lHAwiLDGRotjEFr3ivy8VtY0YTvo6EprWcQb9m/mQ/Je8kuK5vJIXTY0b7ImiS94Iu6s4lweXPU1Wesz9KnkhT6JV8fTCO47BKw5lipfC7GMijIpst+Uii5USVJgzJYvLdiq4KZC7/AKFRLNy/tysTOpFBd4JJ5ur/ZZwlWktr4AuxWfMxx0rBtiF7ZcvK6AyKd2keCR6f8tBd2Q5KVVbZ+fiLxYa5l45Ca2TXOyt5dbplduz4zeKseYS+ilNA+QnUh97aDzLYkeT/xDnkdhwraGnYZ3mr2xo2TYtHO4IFi/n7fay53yT7YiMCe55q0SaeTGeAaymLHAP6kj1Ekh8W3qb8VNOzO7ElFpTVnQZfoJGEmU+N/1DNViwGEcuA8WfOAOD9HhFGmRAOmFBccjHxc6ya5yBk+ZjpEwu5aO4pIvUiSlZL9bm8pmCfG4IfvNsAZ64LL8UTnZu3M6RDE3iPOCdZJBSMuwxoDKk8+NtLoj4VGY7vjFOp3pvHr6g=
# For special logic for cloning submodules on Travis. See
# https://gist.github.com/iedemam/9830045
git:
  submodules: false
# For deploy key setup, see https://github.com/alrra/travis-scripts/blob/master/docs/github-deploy-keys.md
# I used:
# deploykey_enc_key=$(pwgen -s 64)
# ssh-keygen -t rsa -b 4096 -f 'github_deploy_key' -N ''
# openssl aes-256-cbc -k $deploykey_enc_key -in github_deploy_key -out .github_deploy_key.enc
# travis encrypt deploykey_enc_key=$deploykey_enc_key
# [manually add the key above]
before_install:
  - sed -i 's+git@github.com:+https://github.com/+' .gitmodules
  - git submodule update --init --recursive
  - openssl aes-256-cbc -d -k $deploykey_enc_key -in .github_deploy_key.enc -out github_deploy_key
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
  - rm github_deploy_key
after_success: bash deploy.sh
